language: ruby
install: bundle install
cache:
  directories: vendor/bundle
before_script:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n"
  >> ~/.ssh/config
- openssl aes-256-cbc -k "$secret" -in deploy_key.enc -d -a -out deploy.key
- cp deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
script:
- bundle exec danger
